# This is a basic workflow to showcase the use of Reusable Workflows

name: secret sniffle

on:
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Welcome to Baker Hughes!

  docker:
    uses: umangcypher-BH/sturdy-sniffle/.github/workflows/secret santa.yaml@master
    with:
      image_name: umangcypherbh/trivyscan2
      tag: umangcypherbh/trivyscan2
    secrets:
      docker_username: ${{secrets.DOCKER_USERNAME}}
      docker_password: ${{secrets.DOCKER_PASSWORD}}
