name: secret santa

on:
     push:
       branches:
        - "master"
     

jobs:
   build:
      
      runs-on: ubuntu-latest
    
      steps:
      - name: copy template file from  ReusableWorkflow repo
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/umangcypher-BH/sturdy-sniffle.git
      - name: copy the docker file to template directory
        run: |
          cp ${{ inputs.docker_file_path }}./sturdy-sniffle/Dockerfile ./sturdy-sniffle/configs   
      - name: Install Trivy CLI
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.31.3
      - name: downloading  vulnerability  database
        run: |
          /usr/local/bin/trivy image --download-db-only
 

      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Docker Login
        uses: docker/login-action@v2
        with:          
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/trivyscan2:latestv1.0
