name: secret santa

on:
    workflow_call:
     inputs:
      image_name: 
        required: true
        type: string
      tag: 
        type: string
      
     secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!


      -
        name: Checkout
        uses: actions/checkout@v3
        
      - name: Docker Login
        uses: docker/login-action@v2
        with:          
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/trivyscan2:latestv1.0
